export { DashboardTemplate } from './DashboardTemplate';
export type { DashboardTemplateProps, MetricItem } from './DashboardTemplate';
export { TableTemplate } from './TableTemplate';
export type { TableTemplateProps } from './TableTemplate';
export { DetailTemplate } from './DetailTemplate';
export type { DetailTemplateProps, DetailSection } from './DetailTemplate';
export { SettingsTemplate } from './SettingsTemplate';
export type { SettingsTemplateProps, SettingsSection } from './SettingsTemplate';
export { WizardTemplate } from './WizardTemplate';
export type { WizardTemplateProps, WizardStep } from './WizardTemplate';
export { CatalogTemplate } from './CatalogTemplate';
export type { CatalogTemplateProps, CatalogItem } from './CatalogTemplate';
export { BuilderTemplate } from './BuilderTemplate';
export type { BuilderTemplateProps } from './BuilderTemplate';
export { SplitViewTemplate } from './SplitViewTemplate';
export type { SplitViewTemplateProps } from './SplitViewTemplate';
export { EmptyStateTemplate } from './EmptyStateTemplate';
export type { EmptyStateTemplateProps } from './EmptyStateTemplate';
