import type { DashboardManifest } from '@dashboard-bootstrap/schema';

const HEADER = '// @generated — DO NOT EDIT\n// This file is generated by dashboard-bootstrap. Changes will be overwritten.\n';

export function generateDashboardConfig(manifest: DashboardManifest): string {
  const pages = Object.entries(manifest.pages).map(([id, page]) => {
    const caps = page.capabilities
      ? `, capabilities: ${JSON.stringify(page.capabilities)}`
      : '';
    return `  '${id}': { route: '${page.route}', template: '${page.template}'${caps} },`;
  });

  return `${HEADER}
export const dashboardConfig = {
  name: '${manifest.application.name}',
  description: ${manifest.application.description ? `'${manifest.application.description}'` : 'undefined'},
  version: ${manifest.version},
  pages: {
${pages.join('\n')}
  },
};
`;
}
