import type { DashboardManifest, NavigationItem } from '@dashboard-bootstrap/schema';

const HEADER = '// @generated — DO NOT EDIT\n// This file is generated by dashboard-bootstrap. Changes will be overwritten.\n';

function renderNavItem(item: NavigationItem, indent: number): string {
  const pad = ' '.repeat(indent);
  const children = item.children?.length
    ? `,\n${pad}  children: [\n${item.children.map((c) => renderNavItem(c, indent + 4)).join(',\n')}\n${pad}  ]`
    : '';
  return `${pad}{ label: '${item.label}', icon: '${item.icon}', route: '${item.route}'${children} }`;
}

export function generateNavigation(manifest: DashboardManifest): string {
  const items = manifest.navigation.map((item) => renderNavItem(item, 2)).join(',\n');

  return `${HEADER}
export interface NavigationItem {
  label: string;
  icon: string;
  route: string;
  children?: NavigationItem[];
}

export const navigation: NavigationItem[] = [
${items}
];
`;
}
