import type { DashboardManifest } from '@dashboard-bootstrap/schema';

const HEADER = '// @generated — DO NOT EDIT\n// This file is generated by dashboard-bootstrap. Changes will be overwritten.\n';

export function generatePackageJson(manifest: DashboardManifest): string {
  const pkg = {
    name: manifest.application.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc && vite build',
      preview: 'vite preview',
    },
    dependencies: {
      '@dashboard-bootstrap/design-system': 'latest',
      '@dashboard-bootstrap/templates': 'latest',
      '@mui/material': '^6.4.0',
      '@emotion/react': '^11.14.0',
      '@emotion/styled': '^11.14.0',
      'react': '^19.0.0',
      'react-dom': '^19.0.0',
      'react-router-dom': '^7.6.0',
    },
    devDependencies: {
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      '@vitejs/plugin-react': '^4.4.0',
      'typescript': '^5.7.0',
      'vite': '^6.3.0',
    },
  };
  return JSON.stringify(pkg, null, 2) + '\n';
}

export function generateIndexHtml(manifest: DashboardManifest): string {
  const title = manifest.application.name;
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

export function generateViteConfig(): string {
  return `${HEADER}
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
}

export function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      jsx: 'react-jsx',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      outDir: 'dist',
      declaration: false,
    },
    include: ['src'],
  }, null, 2) + '\n';
}

export function generateMainTsx(): string {
  return `${HEADER}
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
);
`;
}

function buildSections(items: DashboardManifest['navigation'], position: 'top' | 'bottom'): string {
  const filtered = items.filter((item) => (item.position ?? 'top') === position);
  if (filtered.length === 0) return '[]';

  // Group items: items without a group key go into a section with no label.
  // Items with the same group key are grouped under a labeled section.
  // Preserve order of first appearance.
  const groups: { label: string | undefined; items: typeof filtered }[] = [];
  const groupIndex = new Map<string | undefined, number>();

  for (const item of filtered) {
    const key = item.group ?? undefined;
    const idx = groupIndex.get(key);
    if (idx !== undefined) {
      groups[idx].items.push(item);
    } else {
      groupIndex.set(key, groups.length);
      groups.push({ label: key, items: [item] });
    }
  }

  const sectionStrings = groups.map((g) => {
    const itemLines = g.items
      .map((item) => `      { label: '${item.label}', icon: '${item.icon}', route: '${item.route}' },`)
      .join('\n');
    const labelPart = g.label ? `\n    label: '${g.label}',` : '';
    return `  {${labelPart}
    items: [
${itemLines}
    ],
  }`;
  });

  return `[\n${sectionStrings.join(',\n')},\n]`;
}

export function generateAppTsx(manifest: DashboardManifest): string {
  const topSections = buildSections(manifest.navigation, 'top');
  const bottomSections = buildSections(manifest.navigation, 'bottom');
  const hasBottom = manifest.navigation.some((item) => item.position === 'bottom');

  const app = manifest.application;
  const hasLogoConfig = app.logo || app.collapsedLogo || app.companyName;

  const logoConfigLines: string[] = [];
  if (hasLogoConfig) {
    logoConfigLines.push('const logoConfig: SidebarLogoConfig = {');
    if (app.companyName) logoConfigLines.push(`  companyName: '${app.companyName}',`);
    if (app.logo) logoConfigLines.push(`  logo: '${app.logo}',`);
    if (app.collapsedLogo) logoConfigLines.push(`  collapsedLogo: '${app.collapsedLogo}',`);
    logoConfigLines.push('};');
  }

  return `${HEADER}
import React from 'react';
import { Routes, Route, useNavigate, useLocation } from 'react-router-dom';
import { DashboardThemeProvider, AppShell } from '@dashboard-bootstrap/design-system';
import type { SidebarSection, SidebarLogoConfig } from '@dashboard-bootstrap/design-system';
import { routes } from './generated/routes.generated';
import { themeColors } from './generated/theme.generated';

const sections: SidebarSection[] = ${topSections};
${hasBottom ? `\nconst bottomSections: SidebarSection[] = ${bottomSections};\n` : ''}${hasLogoConfig ? `\n${logoConfigLines.join('\n')}\n` : ''}
export default function App() {
  const navigate = useNavigate();
  const location = useLocation();

  return (
    <DashboardThemeProvider themeColors={themeColors}>
      <AppShell
        sections={sections}
        activeRoute={location.pathname}
        onNavigate={(route) => navigate(route)}${hasBottom ? '\n        bottomSections={bottomSections}' : ''}${hasLogoConfig ? '\n        logoConfig={logoConfig}' : ''}
      >
        <Routes>
          {routes.map((r) => (
            <Route key={r.path} path={r.path} element={r.element} />
          ))}
        </Routes>
      </AppShell>
    </DashboardThemeProvider>
  );
}
`;
}
