import type { DashboardManifest } from '@dashboard-bootstrap/schema';

const HEADER = '// @generated — DO NOT EDIT\n// This file is generated by dashboard-bootstrap. Changes will be overwritten.\n';

function pageComponentName(pageId: string): string {
  return pageId.charAt(0).toUpperCase() + pageId.slice(1).replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + 'Page';
}

export function generateRoutes(manifest: DashboardManifest): string {
  const pages = Object.entries(manifest.pages);
  const imports = pages
    .map(([id]) => {
      const comp = pageComponentName(id);
      return `import { default as ${comp} } from '../pages/${comp}';`;
    })
    .join('\n');

  const routeEntries = pages
    .map(([id, page]) => {
      const comp = pageComponentName(id);
      return `  { path: '${page.route}', element: <${comp} /> },`;
    })
    .join('\n');

  return `${HEADER}
import React from 'react';

${imports}

export interface AppRoute {
  path: string;
  element: React.ReactNode;
}

export const routes: AppRoute[] = [
${routeEntries}
];
`;
}

export { pageComponentName };
