import type { DashboardManifest } from '@dashboard-bootstrap/schema';

const HEADER = '// @generated — DO NOT EDIT\n// This file is generated by dashboard-bootstrap. Changes will be overwritten.\n';

interface ResolvedColors {
  primary: string;
  primaryHover: string;
  primarySoft: string;
  complete: string;
  completeText: string;
}

const presets: Record<string, ResolvedColors> = {
  purple: {
    primary: '#5425E5',
    primaryHover: '#461CCB',
    primarySoft: '#EEE9FF',
    complete: '#F6E65A',
    completeText: '#111111',
  },
  orange: {
    primary: '#E85D04',
    primaryHover: '#CC5203',
    primarySoft: '#FFF3E6',
    complete: '#F6E65A',
    completeText: '#111111',
  },
  blue: {
    primary: '#2563EB',
    primaryHover: '#1D4ED8',
    primarySoft: '#EFF6FF',
    complete: '#F6E65A',
    completeText: '#111111',
  },
  green: {
    primary: '#059669',
    primaryHover: '#047857',
    primarySoft: '#ECFDF5',
    complete: '#F6E65A',
    completeText: '#111111',
  },
  red: {
    primary: '#DC2626',
    primaryHover: '#B91C1C',
    primarySoft: '#FEF2F2',
    complete: '#F6E65A',
    completeText: '#111111',
  },
  teal: {
    primary: '#0D9488',
    primaryHover: '#0F766E',
    primarySoft: '#F0FDFA',
    complete: '#F6E65A',
    completeText: '#111111',
  },
  pink: {
    primary: '#DB2777',
    primaryHover: '#BE185D',
    primarySoft: '#FDF2F8',
    complete: '#F6E65A',
    completeText: '#111111',
  },
};

function resolveColors(theme?: string | { preset: string; colors?: Partial<ResolvedColors> }): ResolvedColors {
  if (!theme) return presets.purple;

  const presetName = typeof theme === 'string' ? theme : theme.preset;
  const base = presets[presetName] ?? presets.purple;

  if (typeof theme === 'object' && theme.colors) {
    return { ...base, ...theme.colors };
  }

  return base;
}

export function generateThemeConfig(manifest: DashboardManifest): string {
  const colors = resolveColors(manifest.application.theme);

  return `${HEADER}
import type { ThemeColors } from '@dashboard-bootstrap/design-system';

export const themeColors: ThemeColors = {
  primary: '${colors.primary}',
  primaryHover: '${colors.primaryHover}',
  primarySoft: '${colors.primarySoft}',
  complete: '${colors.complete}',
  completeText: '${colors.completeText}',
};
`;
}
