/**
 * Canonical manifest vocabulary for Dashboard Bootstrap.
 * This package is the sole owner of TemplateName, IconName, and capability identifiers.
 */

export const TEMPLATE_NAMES = [
  'dashboard',
  'table',
  'detail',
  'settings',
  'wizard',
  'catalog',
  'builder',
  'split-view',
  'empty-state',
] as const;

export type TemplateName = (typeof TEMPLATE_NAMES)[number];

export const ICON_NAMES = [
  'activity',
  'alert-circle',
  'alert-triangle',
  'archive',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'bar-chart',
  'bell',
  'book',
  'bookmark',
  'box',
  'briefcase',
  'building',
  'calendar',
  'check',
  'check-circle',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'circle',
  'clipboard',
  'clock',
  'cloud',
  'code',
  'cog',
  'copy',
  'credit-card',
  'database',
  'dollar-sign',
  'download',
  'edit',
  'external-link',
  'eye',
  'file',
  'file-text',
  'filter',
  'flag',
  'folder',
  'globe',
  'grid',
  'hash',
  'heart',
  'help-circle',
  'home',
  'image',
  'inbox',
  'info',
  'key',
  'layers',
  'layout',
  'link',
  'list',
  'lock',
  'log-out',
  'mail',
  'map',
  'map-pin',
  'menu',
  'message-circle',
  'minus',
  'monitor',
  'more-horizontal',
  'more-vertical',
  'package',
  'paperclip',
  'pause',
  'percent',
  'phone',
  'pie-chart',
  'play',
  'plus',
  'plus-circle',
  'power',
  'printer',
  'refresh-cw',
  'save',
  'search',
  'send',
  'server',
  'settings',
  'share',
  'shield',
  'shopping-cart',
  'slash',
  'sliders',
  'smartphone',
  'star',
  'stop-circle',
  'sun',
  'tag',
  'target',
  'terminal',
  'thumbs-down',
  'thumbs-up',
  'trash',
  'trending-down',
  'trending-up',
  'truck',
  'unlock',
  'upload',
  'user',
  'user-plus',
  'users',
  'x',
  'x-circle',
  'zap',
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export const THEME_PRESET_NAMES = [
  'purple',
  'orange',
  'blue',
  'green',
  'red',
  'teal',
  'pink',
] as const;

export type ThemePresetName = (typeof THEME_PRESET_NAMES)[number];

/**
 * Capability definitions per template type.
 * Keys are TemplateName values; values are arrays of valid capability identifiers.
 */
export const CAPABILITIES: Record<TemplateName, readonly string[]> = {
  dashboard: ['metrics', 'activity-feed', 'quick-actions', 'charts'],
  table: ['search', 'filters', 'sorting', 'pagination', 'row-actions', 'bulk-actions', 'export'],
  detail: ['tabs', 'sidebar', 'actions', 'breadcrumbs', 'related-items'],
  settings: ['sections', 'save-confirmation', 'reset', 'validation'],
  wizard: ['steps', 'validation', 'progress-bar', 'save-draft'],
  catalog: ['grid-view', 'list-view', 'filters', 'search', 'sorting', 'pagination'],
  builder: ['drag-drop', 'preview', 'undo-redo', 'save', 'toolbar'],
  'split-view': ['resizable', 'list-detail', 'filters', 'search'],
  'empty-state': ['illustration', 'action-button', 'description'],
};
